-- ROWBOAT JOBS PLATFORM
-- Run this once in Supabase SQL Editor.
create extension if not exists pgcrypto;
create table if not exists public.jobs (id uuid primary key default gen_random_uuid(),title text not null,company text,module text,industry text,location text,experience text,type text default 'Full-time',openings integer default 1,salary text,description text,requirements text,responsibilities text,skills text[] default '{}',apply_email text,reference_code text,status text not null default 'draft' check (status in ('draft','open','closed')),published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.applications (id uuid primary key default gen_random_uuid(),job_id uuid references public.jobs(id) on delete set null,full_name text not null,email text not null,phone text,resume_url text,linkedin_url text,cover_letter text,status text not null default 'new' check (status in ('new','reviewing','shortlisted','rejected','hired')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists jobs_status_idx on public.jobs(status); create index if not exists jobs_module_idx on public.jobs(module); create index if not exists jobs_created_at_idx on public.jobs(created_at desc); create index if not exists applications_job_id_idx on public.applications(job_id); create index if not exists applications_created_at_idx on public.applications(created_at desc);
alter table public.jobs enable row level security; alter table public.applications enable row level security;
drop policy if exists "Public can read open jobs" on public.jobs; create policy "Public can read open jobs" on public.jobs for select to anon, authenticated using (status = 'open');
drop policy if exists "Authenticated can manage jobs" on public.jobs; create policy "Authenticated can manage jobs" on public.jobs for all to authenticated using (true) with check (true);
drop policy if exists "Public can submit applications" on public.applications; create policy "Public can submit applications" on public.applications for insert to anon, authenticated with check (true);
drop policy if exists "Authenticated can manage applications" on public.applications; create policy "Authenticated can manage applications" on public.applications for select, update, delete to authenticated using (true) with check (true);
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists jobs_set_updated_at on public.jobs; create trigger jobs_set_updated_at before update on public.jobs for each row execute function public.set_updated_at();
drop trigger if exists applications_set_updated_at on public.applications; create trigger applications_set_updated_at before update on public.applications for each row execute function public.set_updated_at();
