'use client'

import { useMemo, useState } from 'react'

const jobs = [
  { title:'Senior Full Stack Engineer', company:'Confidential Client', location:'Bengaluru, India', type:'Full-time', mode:'Hybrid', category:'Technology' },
  { title:'React / Next.js Developer', company:'ROWBOAT Opportunity', location:'Chennai, India', type:'Contract', mode:'Remote', category:'Technology' },
  { title:'Talent Acquisition Specialist', company:'Growing Enterprise', location:'Hyderabad, India', type:'Full-time', mode:'On-site', category:'Recruitment' },
  { title:'Data Analyst — Power BI', company:'Confidential Client', location:'Pune, India', type:'Full-time', mode:'Hybrid', category:'Data' },
  { title:'SAP FICO Consultant', company:'Enterprise Project', location:'Mumbai, India', type:'Contract', mode:'Remote', category:'ERP' },
  { title:'Product Designer', company:'ROWBOAT Project', location:'India', type:'Freelance', mode:'Remote', category:'Design' },
]

export default function Home() {
  const [query,setQuery]=useState(''); const [location,setLocation]=useState(''); const [type,setType]=useState('')
  const filtered=useMemo(()=>jobs.filter(j=>`${j.title} ${j.company} ${j.category}`.toLowerCase().includes(query.toLowerCase()) && (!location||j.location.toLowerCase().includes(location.toLowerCase())) && (!type||j.type===type)),[query,location,type])
  return <>
    <nav className="nav"><div className="container navInner"><a className="brand" href="#top"><span className="mark">R</span><span>ROWBOAT <span style={{fontWeight:500}}>JOBS</span></span></a><div className="navLinks"><a href="#jobs">Find Jobs</a><a href="#talent">Hire Talent</a><a href="#about">How it works</a><a className="navCta" href="mailto:careers@rowboatcs.com?subject=ROWBOAT%20JOBS%20Talent%20Hub">Recruiter Login</a></div><span className="mobileOnly">☰</span></div></nav>
    <main id="top">
      <section className="hero"><div className="container"><div className="eyebrow">Jobs • Projects • Talent</div><h1>Find the right opportunity.<br/>Build the right team.</h1><p>ROWBOAT JOBS connects people and businesses through curated jobs, freelance projects and talent solutions — starting in India, built for the world.</p><div className="heroActions"><a className="btn btnPrimary" href="#jobs">Explore opportunities →</a><a className="btn btnLight" href="#talent">Hire Talent</a></div><div className="searchBox"><input className="input" placeholder="Job title, skill or keyword" value={query} onChange={e=>setQuery(e.target.value)}/><input className="input" placeholder="Location" value={location} onChange={e=>setLocation(e.target.value)}/><select className="input" value={type} onChange={e=>setType(e.target.value)}><option value="">All job types</option><option>Full-time</option><option>Contract</option><option>Freelance</option></select><button className="btn btnPrimary" onClick={()=>document.getElementById('jobs')?.scrollIntoView()}>Search</button></div></div></section>
      <section className="section" id="jobs"><div className="container"><div className="sectionHead"><div><div className="eyebrow">Latest opportunities</div><h2>Roles worth exploring</h2><div className="muted">Curated opportunities across technology, business and specialist functions.</div></div><div className="muted">{filtered.length} opportunities</div></div>{filtered.length?<div className="jobs">{filtered.map((j,i)=><article className="job" key={i}><span className="tag">{j.type}</span><h3>{j.title}</h3><div className="jobMeta">{j.company}<br/>{j.location} · {j.mode}</div><div className="jobFoot"><span>{j.category}</span><a href={`mailto:careers@rowboatcs.com?subject=Apply%20for%20${encodeURIComponent(j.title)}`}>View role <span className="arrow">→</span></a></div></article>)}</div>:<div className="empty">No opportunities match those filters. Try a broader search.</div>}</div></section>
      <section className="section" id="talent"><div className="container"><div className="split"><div className="panel"><div className="eyebrow" style={{color:'#8ee0bd'}}>For employers</div><h3>Need great people?</h3><p>Tell ROWBOAT what you need. Our recruiters can source, screen and manage the hiring process around your requirements.</p><a className="btn btnLight" href="mailto:careers@rowboatcs.com?subject=Hire%20Talent%20with%20ROWBOAT">Submit a requirement →</a></div><div className="panel light"><div className="eyebrow">For candidates</div><h3>Keep your next move open.</h3><p>Build your profile, share your resume and let the right opportunities find you. Candidate tools are being rolled out in the private Talent Hub.</p><a className="btn btnPrimary" href="mailto:careers@rowboatcs.com?subject=Join%20ROWBOAT%20Talent%20Hub">Join the talent network →</a></div></div></div></section>
      <section className="section" id="about"><div className="container"><div className="sectionHead"><div><div className="eyebrow">Built to grow</div><h2>More than a job board.</h2><div className="muted" style={{maxWidth:720}}>ROWBOAT JOBS is being built as a recruitment operating platform: public opportunities on the outside, a secure Talent Hub and client CRM on the inside, with matching and placement workflows underneath.</div></div></div></div></section>
    </main><footer className="footer"><div className="container">© 2026 ROWBOAT JOBS · A ROWBOAT initiative · India-first, globally extensible</div></footer>
  </>
}
