'use client'

export default function Home() {
  return <>
    <nav className="nav"><div className="container navInner"><a className="brand" href="#top"><span className="mark">R</span><span>ROWBOAT <span style={{fontWeight:500}}>CONSULTING SERVICES</span></span></a><div className="navLinks"><a href="#careers">Careers</a><a href="#talent">Hire Talent</a><a href="#about">How it works</a><a className="navCta" href="mailto:careers@rowboatcs.com?subject=Careers%20at%20ROWBOAT">Contact</a></div><span className="mobileOnly">☰</span></div></nav>
    <main id="top">
      <section className="hero"><div className="container"><div className="eyebrow">Consulting • Talent • Careers</div><h1>Building better teams.<br/>Creating better opportunities.</h1><p>ROWBOAT CONSULTING SERVICES helps businesses solve complex needs through consulting, talent and specialist services.</p><div className="heroActions"><a className="btn btnPrimary" href="#careers">Explore Careers →</a><a className="btn btnLight" href="#talent">Hire Talent</a></div></div></section>
      <section className="section" id="careers"><div className="container"><div className="sectionHead"><div><div className="eyebrow">ROWBOAT JOBS</div><h2>Careers at ROWBOAT</h2><div className="muted">Career opportunities will be published here as they become available.</div></div></div><div className="empty">No open positions are currently listed.</div></div></section>
      <section className="section" id="talent"><div className="container"><div className="split"><div className="panel"><div className="eyebrow" style={{color:'#8ee0bd'}}>For employers</div><h3>Need great people?</h3><p>Tell ROWBOAT what you need. Our recruiters can source, screen and manage the hiring process around your requirements.</p><a className="btn btnLight" href="mailto:careers@rowboatcs.com?subject=Hire%20Talent%20with%20ROWBOAT">Submit a requirement →</a></div><div className="panel light"><div className="eyebrow">For candidates</div><h3>Keep your next move open.</h3><p>Share your resume and career interests with ROWBOAT CONSULTING SERVICES for future opportunities.</p><a className="btn btnPrimary" href="mailto:careers@rowboatcs.com?subject=Careers%20at%20ROWBOAT">Contact Careers →</a></div></div></div></section>
      <section className="section" id="about"><div className="container"><div className="sectionHead"><div><div className="eyebrow">About ROWBOAT</div><h2>Consulting with a people-first approach.</h2><div className="muted" style={{maxWidth:720}}>ROWBOAT CONSULTING SERVICES delivers consulting and talent solutions designed around the needs of clients and candidates.</div></div></div></div></section>
    </main><footer className="footer"><div className="container">© 2026 ROWBOAT CONSULTING SERVICES · India-first, globally extensible</div></footer>
  </>
}
