import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '../../../lib/supabase/server'

export const dynamic = 'force-dynamic'

function cleanJob(input: Record<string, unknown>) { return { title:String(input.title||'').trim(), company:String(input.company||'').trim()||null, module:String(input.module||'').trim()||null, industry:String(input.industry||'').trim()||null, location:String(input.location||'').trim()||null, experience:String(input.experience||'').trim()||null, type:String(input.type||'').trim()||'Full-time', openings:Number(input.openings||1), salary:String(input.salary||'').trim()||null, description:String(input.description||'').trim()||null, requirements:String(input.requirements||'').trim()||null, responsibilities:String(input.responsibilities||'').trim()||null, skills:Array.isArray(input.skills)?input.skills.map(String).map(s=>s.trim()).filter(Boolean):[], apply_email:String(input.apply_email||'').trim()||null, reference_code:String(input.reference_code||'').trim()||null, status:['draft','open','closed'].includes(String(input.status))?String(input.status):'draft', published_at:input.status==='open'?(input.published_at||new Date().toISOString()):null } }
async function auth(){ const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); return {supabase,user} }
export async function GET(request:NextRequest){ const admin=request.nextUrl.searchParams.get('admin')==='1'; const {supabase,user}=await auth(); if(admin&&!user)return NextResponse.json({error:'Sign in required'},{status:401}); let query=supabase.from('jobs').select('*').order('created_at',{ascending:false}); if(!admin)query=query.eq('status','open'); const {data,error}=await query; if(error)return NextResponse.json({error:error.message},{status:500,headers:{'Cache-Control':'no-store'}}); return NextResponse.json({jobs:data||[]},{headers:{'Cache-Control':'no-store'}}) }
export async function POST(request:NextRequest){ const {supabase,user}=await auth(); if(!user)return NextResponse.json({error:'Sign in required'},{status:401}); const job=cleanJob(await request.json()); if(!job.title)return NextResponse.json({error:'Job title is required'},{status:400}); const {data,error}=await supabase.from('jobs').insert(job).select('*').single(); if(error)return NextResponse.json({error:error.message},{status:500}); return NextResponse.json({job:data}) }
