import { NextRequest, NextResponse } from 'next/server'
import { getAuthContext } from '../../../lib/supabase/authorization'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

function staffOnly(role: string | null) {
  return role === 'admin' || role === 'super_admin' || role === 'recruiter'
}
function text(value: unknown) { return typeof value === 'string' ? value.trim() : '' }
function normalized(value: unknown) { return text(value).toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim() }
function digits(value: unknown) { return text(value).replace(/\D/g, '') }
function list(value: unknown) { return Array.isArray(value) ? value.map(v => String(v).trim()).filter(Boolean) : text(value).split(',').map(v => v.trim()).filter(Boolean) }
function num(value: unknown) { const n = Number(value); return Number.isFinite(n) ? n : null }
function searchable(c: any) { return [c.full_name,c.email,c.phone,c.country,c.state,c.city,c.metro_area,c.location,c.technology,c.primary_skill,...(c.secondary_skills||[]),c.industry,c.current_company,c.candidate_current_role,...(c.previous_companies||[]),...(c.certifications||[]),...(c.projects||[]),...(c.education_text||[]),...(c.technical_responsibilities||[]),...(c.management_responsibilities||[]),...(c.achievements_text||[])].filter(Boolean).join(' ').toLowerCase() }
function mapCandidate(c: any) { return { candidate_id:c.id, talent:{technology:c.technology,primary_skill:c.primary_skill,secondary_skills:c.secondary_skills||[],industry:c.industry,previous_companies:c.previous_companies||[],employment_type:c.employment_type,work_authorization:c.work_authorization,certifications:c.certifications||[],projects:c.projects||[],education:c.education_text||c.education||[],technical_responsibilities:c.technical_responsibilities||[],management_responsibilities:c.management_responsibilities||[],achievements:c.achievements_text||c.achievements||[],current_role:c.candidate_current_role||c.current_role,relevant_experience_years:c.relevant_experience_years,availability:c.availability,ai_generated_skill_profile:c.ai_summary,candidate_status:c.candidate_status,source:c.source,recruiter:c.recruiter,recruiter_notes:c.recruiter_notes},profile:{id:c.id,full_name:c.full_name,email:c.email,phone:c.phone,location:c.location,country:c.country,state:c.state,city:c.city,metro_area:c.metro_area,current_company:c.current_company,experience_years:c.years_experience,relevant_experience_years:c.relevant_experience_years,notice_period_days:c.notice_period_days,resume_url:c.resume_storage_path?`storage:${c.resume_storage_path}`:null,resume_file_name:c.resume_file_name,linkedin_url:c.linkedin_url,current_ctc:c.current_compensation,expected_ctc:c.expected_compensation,candidate_status:c.candidate_status}} }
function dedupe(rows:any[]){const seen=new Set<string>();return rows.filter(r=>{const e=normalized(r.email);const p=digits(r.phone);const n=normalized(r.full_name);const key=e?`e:${e}`:p?`p:${p}`:n?`n:${n}`:`id:${r.id}`;if(seen.has(key))return false;seen.add(key);return true})}
async function getRows(supabase:any){const {data,error}=await supabase.from('talent_pool_candidates').select('*').order('updated_at',{ascending:false}).limit(1000);if(error)throw new Error(error.message);return data||[]}

export async function GET(request:NextRequest){const {supabase,user,role}=await getAuthContext();if(!user)return NextResponse.json({error:'Sign in required'},{status:401});if(!staffOnly(role))return NextResponse.json({error:'Admin/recruiter access required'},{status:403});try{let rows=dedupe(await getRows(supabase));const q=normalized(request.nextUrl.searchParams.get('search'));if(q)rows=rows.filter(r=>searchable(r).includes(q));return NextResponse.json({candidates:rows.map(mapCandidate),total:rows.length})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to load talent database'},{status:500})}}

export async function POST(request:NextRequest){const {supabase,user,role}=await getAuthContext();if(!user)return NextResponse.json({error:'Sign in required'},{status:401});if(!staffOnly(role))return NextResponse.json({error:'Admin/recruiter access required'},{status:403});try{const body=await request.json();const location=normalized(body.location);const country=normalized(body.country);const state=normalized(body.state);const city=normalized(body.city);const metro=normalized(body.metro);const skills=list(body.skills).map(normalized).filter(Boolean);const minExp=num(body.experienceMin);const minRelevant=num(body.relevantExperienceMin);const maxNotice=num(body.noticeDays);const query=normalized(body.query||'');let rows=dedupe(await getRows(supabase));rows=rows.filter((r:any)=>{const hay=searchable(r);const loc=[r.location,r.country,r.state,r.city,r.metro_area].filter(Boolean).map(normalized).join(' ');if(query&&!hay.includes(query))return false;if(country&&!normalized(r.country).includes(country)&&!loc.includes(country))return false;if(state&&!normalized(r.state).includes(state)&&!loc.includes(state))return false;if(city&&!normalized(r.city).includes(city)&&!loc.includes(city))return false;if(metro&&!normalized(r.metro_area).includes(metro)&&!loc.includes(metro))return false;if(location&&!loc.includes(location)&&!normalized(r.location).includes(location))return false;if(minExp!=null&&!(Number(r.years_experience)>=minExp))return false;if(minRelevant!=null&&!(Number(r.relevant_experience_years)>=minRelevant))return false;if(maxNotice!=null&&!(Number.isFinite(Number(r.notice_period_days))&&Number(r.notice_period_days)<=maxNotice))return false;for(const s of skills){const fields=[r.technology,r.primary_skill,...(r.secondary_skills||[]),...(r.certifications||[]),...(r.projects||[]),...(r.technical_responsibilities||[])].filter(Boolean).map(normalized);if(!fields.some((f:string)=>f.includes(s)))return false}return true});return NextResponse.json({matches:rows.map(mapCandidate),total:rows.length,requirement:{location,skills,minExp,minRelevant,maxNotice,query},message:rows.length?'Exact search matched all requested filters.':'No candidates matched every requested filter.'})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to search talent database'},{status:500})}}

export async function PATCH(request:NextRequest){const {supabase,user,role}=await getAuthContext();if(!user)return NextResponse.json({error:'Sign in required'},{status:401});if(!staffOnly(role))return NextResponse.json({error:'Admin/recruiter access required'},{status:403});try{const body=await request.json();const id=text(body.candidate_id);if(!id)return NextResponse.json({error:'candidate_id is required'},{status:400});const allowed=['full_name','email','phone','location','country','state','city','metro_area','technology','primary_skill','secondary_skills','years_experience','relevant_experience_years','industry','current_company','candidate_current_role','current_role','previous_companies','notice_period_days','availability','current_compensation','expected_compensation','employment_type','work_authorization','certifications','projects','linkedin_url','education_text','education','technical_responsibilities','management_responsibilities','achievements_text','achievements','candidate_status','source','recruiter','recruiter_notes'];const payload:any={};for(const k of allowed)if(body[k]!==undefined)payload[k]=['secondary_skills','previous_companies','certifications','projects','education_text','education','technical_responsibilities','management_responsibilities','achievements_text','achievements'].includes(k)?list(body[k]):body[k];if(payload.email!==undefined)payload.email_normalized=normalized(payload.email);if(payload.phone!==undefined)payload.phone_normalized=digits(payload.phone);if(payload.full_name!==undefined)payload.name_normalized=normalized(payload.full_name);const {data,error}=await supabase.from('talent_pool_candidates').update(payload).eq('id',id).select('*').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({candidate:mapCandidate(data)})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to update candidate'},{status:500})}}

export async function DELETE(request:NextRequest){const {supabase,user,role}=await getAuthContext();if(!user)return NextResponse.json({error:'Sign in required'},{status:401});if(!staffOnly(role))return NextResponse.json({error:'Admin/recruiter access required'},{status:403});try{const body=await request.json();const id=text(body?.candidate_id);if(!id)return NextResponse.json({error:'candidate_id is required'},{status:400});const {data:candidate,error:readError}=await supabase.from('talent_pool_candidates').select('id,resume_storage_path,full_name').eq('id',id).maybeSingle();if(readError)return NextResponse.json({error:readError.message},{status:500});if(!candidate)return NextResponse.json({error:'Candidate profile not found'},{status:404});const {error:deleteError}=await supabase.from('talent_pool_candidates').delete().eq('id',id);if(deleteError)return NextResponse.json({error:deleteError.message},{status:500});if(candidate.resume_storage_path){const {error:storageError}=await supabase.storage.from('candidate-resumes').remove([candidate.resume_storage_path]);if(storageError)return NextResponse.json({deleted:true,candidate_id:id,full_name:candidate.full_name,warning:`Profile deleted, but resume cleanup failed: ${storageError.message}`})}return NextResponse.json({deleted:true,candidate_id:id,full_name:candidate.full_name})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to permanently delete candidate'},{status:500})}}
